apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agent-manager-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agent-manager
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: External
      external:
        metric:
          name: pending_tasks_per_agent
        target:
          type: AverageValue
          averageValue: 5